var m = require('mithril');
var layout = require('../layout/sidebar.js');

module.exports = function(vm) {
    return layout(m('.page', [
        m('h1', 'Terms of Service'),
        m('p', ['Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the ',
                'https://tldr.gg website (the "Service") operated by TLDR, LLC. ("us", "we", "our", or “company”).']),
        m('p', ['Your access to and use of the Service is conditioned on your acceptance of and compliance with these ',
                'Terms. These Terms apply to all visitors, users and others who access or use the Service.']),
        m('p', ['By accessing or using the Service you agree to be bound by these Terms. If you disagree with any ',
                'part of the terms then you may not access the Service.']),
        m('h2', 'Privacy Policy'),
        m('p', ['We ask that you review the terms of our Privacy Policy, so that you are aware of how we collect and ',
                'use your information. Because our services are used by people all over the world, personal ',
                'information that we collect may be stored and processed in the United States of America or any other ',
                'country in which we or our agents maintain facilities. By using our services, you consent to any ',
                'such transfer of information outside your country.']),
        m('h2', 'Membership'),
        m('p', ['In order to use certain portions of this Service, you will need to first register for membership in ',
                'the Service. You are prohibited from registering for membership in the Service where prohibited by ',
                'law. In addition, the Service is intended solely for users who are thirteen (13) years of age or ',
                'older. Any registration by anyone under 13 is unauthorized, unlicensed and in violation of this ',
                'Agreement. By registering for the Service, you represent and warrant that you are 13 or older and ',
                'that you agree to and to abide by all of the terms and conditions of this Agreement.']),
        m('p', ['If you choose to register for membership, in consideration of your use of the Service, you agree to ',
                'maintain the security of your password and identification and to be fully responsible for all use of ',
                'your account and for any actions that take place using your account.']),
        m('p', ['The Company may terminate your account, delete your profile and any content or information that you ',
                'have posted on the Service and/or prohibit you from using or accessing the Service for any reason, ',
                'or no reason, at any time in its sole discretion, with or without notice.']),
        m('h2', 'Content Hosted by TLDR.gg'),
        m('p', [m('i', 'You may find some material objectionable or erroneous:'), ' Because we provide a wide array ',
                'of content that is produced or gathered by fellow users, you may encounter material that you find ',
                'offensive, erroneous, misleading, mislabeled, or otherwise objectionable. We therefore ask that you ',
                'use common sense and proper judgment when using our services.']),
        m('p', [m('i', 'Our content is for general informational purposes only:'), ' Although we host a great deal of ',
                'information that pertains to professional topics, this content is presented for general informational ',
                'purposes only. It should not be taken as professional advice. Please seek independent professional ',
                'counseling from someone who is licensed or qualified in the applicable area in lieu of acting on any ',
                'information, opinion, or advice contained in one of the categories.']),
        m('h2', 'Refraining from Certain Activities'),
        m('p', ['The guides hosted by the Company only exist because of our vibrant community. We happily welcome ',
                'your participation in this community. We encourage you to be civil and polite in your interactions ',
                'with others in the community, to act in good faith, and to make edits and contributions aimed at ',
                'furthering the mission of the shared Project.']),
        m('p', ['Certain activities, whether legal or illegal, may be harmful to other users and violate our rules, ',
                'and some activities may also subject you to liability. Therefore, for your own protection and for ',
                'that of other users, you may not engage in such activities on our sites. These activities include:']),
        m('h3', 'Harassing and Abusing Others'),
        m('ul', [
            m('li', 'Engaging in harassment, threats, stalking, spamming, or vandalism.'),
            m('li', 'Transmitting chain mail, junk mail, or spam to other users.')
        ]),
        m('h3', 'Violating the Privacy of Others'),
        m('ul', [
            m('li', 'Infringing the privacy rights of others under the laws of the United States of America or other ',
                'applicable laws (which may include the laws where you live or where you view or edit content.'),
            m('li', 'Soliciting personally identifiable information for purposes of harassment, exploitation, ',
                'violation of privacy, or any promotional or commercial purpose not explicitly approved by the Company.'),
            m('li', 'Soliciting personally identifiable information from anyone under the age of 18 for an illegal ',
                'purpose or violating any applicable law regarding the health or well-being of minors.')
        ]),
        m('h3', 'Engaging in False Statements, Impersonation, or Fraud'),
        m('ul', [
            m('li', 'Intentionally or knowingly posting content that constitutes libel or defamation.'),
            m('li', 'With the intent to deceive, posting content that is false or inaccurate.'),
            m('li', 'Attempting to impersonate another user or individual, misrepresenting your affiliation with any ',
                'individual or entity, or using the username of another user with the intent to deceive.'),
            m('li', 'Engaging in fraud.')
        ]),
        m('h3', 'Committing Infringement'),
        m('ul', [
            m('li', 'Infringing copyrights, trademarks, patents, or other proprietary rights under applicable law.')
        ]),
        m('h3', 'Misusing Our Services for Other Illegal Purposes'),
        m('ul', [
            m('li', 'Posting child pornography or any other content that violates applicable law concerning child pornography.'),
            m('li', 'Posting or trafficking in obscene material that is unlawful under applicable law.'),
            m('li', 'Using the services in a manner that is inconsistent with applicable law.')
        ]),
        m('h3', 'Engaging in Disruptive and Illegal Misuse of Facilities'),
        m('ul', [
            m('li', 'Posting or distributing content that contains any viruses, malware, worms, Trojan horses, ',
                'malicious code, or other device that could harm our technical infrastructure or system or that of our users.'),
            m('li', 'Engaging in automated uses of the site that are abusive or disruptive of the services and have ',
                'not been approved by the Company.'),
            m('li', 'Disrupting the services by placing an undue burden on the networks or servers connected with the Service.'),
            m('li', 'Disrupting the services by inundating any of the websites with communications or other traffic ',
                'that suggests no serious intent to use the website for its stated purpose.'),
            m('li', 'Knowingly accessing, tampering with, or using any of our non-public areas in our computer systems ',
                'without authorization.'),
            m('li', ['Probing, scanning, or testing the vulnerability of any of our technical systems or networks ',
                'unless all the following conditions are met:',
                m('ul', [
                    m('li', 'such actions do not unduly abuse or disrupt our technical systems or networks;'),
                    m('li', 'such actions are not for personal gain (except for credit for your work);'),
                    m('li', 'you report any vulnerabilities to TLDR.gg developers;'),
                    m('li', 'you do not undertake such actions with malicious or destructive intent.')
                ])
            ])
        ]),
        m('h2', 'Links To Other Web Sites'),
        m('p', ['Our Service may contain links to third­ party websites or services that are not owned or controlled ',
                'by TLDR, LLC. The Company has no control over, and assumes no responsibility for, the content, ',
                'privacy policies, or practices of any third party websites or services. You further acknowledge and ',
                'agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or ',
                'loss caused or alleged to be caused by or in connection with use of or reliance on any such content, ',
                'goods or services available on or through any such websites or services. We strongly advise you to ',
                'read the terms and conditions and privacy policies of any third­ party websites or services that you visit.']),
        m('h2', 'Disclaimers and Limitation on Liability'),
        m('p', ['TLDR, LLC does not control and is not responsible and is not liable in any manner for any user ',
                'content submitted to the service.']),
        m('p', ['We provide these services on an "as is" and "as available" basis, and we expressly disclaim all ',
                'express or implied warranties of all kinds, including but not limited to the implied warranties of ',
                'merchantability, fitness for a particular purpose, and non-infringement. We make no warranty that ',
                'our services will meet your requirements, be safe, secure, uninterrupted, timely, accurate, or ',
                'error-free, or that your information will be secure.']),
        m('p', ['We are not responsible for the content, data, or actions of third parties, and you release us, our ',
                'directors, officers, employees, and agents from any claims and damages, known and unknown, arising ',
                'out of or in any way connected with any claim you have against any such third parties. No advice or ',
                'information, whether oral or written, obtained by you from us or through or from our services ',
                'creates any warranty not expressly stated in these Terms of Use.']),
        m('p', ['Any material downloaded or otherwise obtained through your use of our services is done at your own ',
                'discretion and risk, and you will be solely responsible for any damage to your computer system or ',
                'loss of data that results from the download of any such material. You agree that we have no ',
                'responsibility or liability for the deletion of, or the failure to store or to transmit, any content ',
                'or communication maintained by the service. We retain the right to create limits on use and storage ',
                'at our sole discretion at any time with or without notice.']),
        m('p', ['Some states or jurisdictions do not allow the types of disclaimers in this section, so they may not ',
                'apply to you either in part or in full depending on the law.']),
        m('p', ['The Company will not be liable to you or to any other party for any direct, indirect, incidental, ',
                'special, consequential or exemplary damages, including but not limited to, damages for loss of ',
                'profits, goodwill, use, data, or other intangible losses, regardless of whether we were advised of ',
                'the possibility of such damage. In no event shall our liability exceed one thousand U.S. dollars ',
                '(USD 1000.00) in aggregate. In the case that applicable law may not allow the limitation or ',
                'exclusion of liability or incidental or consequential damages, the above limitation or exclusion may ',
                'not apply to you, although our liability will be limited to the fullest extent permitted by applicable law.']),
        m('h2', 'Governing Law'),
        m('p', ['These Terms shall be governed and construed in accordance with the laws of the State of Washington, ',
                'without regard to its conflict of law provisions. Our failure to enforce any right or provision of ',
                'these Terms will not be considered a waiver of those rights. If any provision of these Terms is held ',
                'to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect.']),
        m('p', ['These Terms constitute the entire agreement between us regarding our Service, and supersede and ',
                'replace any prior agreements we might have between us regarding the Service.']),
        m('h2', 'Changes'),
        m('p', ['We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a ',
                'revision is material we will try to provide at least 30 days notice prior to any new terms taking ',
                'effect. What constitutes a material change will be determined at our sole discretion.']),
        m('p', ['By continuing to access or use our Service after those revisions become effective, you agree to be ',
                'bound by the revised terms. If you do not agree to the new terms, please stop using the Service. ']),
        m('h2', 'Contact Us'),
        m('p', 'If you have any questions about these Terms, please contact us.'),
        m('p', ['Text is available under the ',
                m('a[href=https://creativecommons.org/licenses/by-sa/3.0/]', 'Creative Commons Attribution-ShareAlike License'),
                '. Some sections originally found at the ',
                m('a[href=https://wikimediafoundation.org/wiki/Terms_of_Use]', 'Wikimedia Foundation Terms of Service'),
                '.'])
    ]));
};